name: Run VRT
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - '.storybook/**'
      - 'package.json'
      - 'package-lock.json'
      - '.node-version'
      - 'regconfig.json'
    types:
      - opened
      - synchronize
      - reopened
jobs:
  vrt:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.UPLOAD_S3_FOR_VRT_RESULT_ROLE }}
          aws-region: ap-northeast-1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: workaround for detached HEAD for reg-suit
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run storycap
        run: npm run screenshot:ci
      - name: Run reg-suit
        env:
          REG_SUIT_CLIENT_ID: ${{ secrets.REG_SUIT_CLIENT_ID }}
          REG_SUIT_S3_BUCKET_NAME: ${{ secrets.REG_SUIT_S3_BUCKET_NAME }}
        run: npm run regression
